### ISSUE TITLE
doclink capability disable footer js lib loading

### ISSUE THREAD

**Issue by jgribonvald** [GIP-RECIA/moodle-themes-locaux#1]
le fait d'avoir supprimé la capability sur page_doc_link supprime le chargement en footer des librairies dont jquery, et donc la navigation n'est plus possible.

Dans `theme/esco/templates/footer.mustache` le problème est que l'affichage complet de l'élément `output.standard_end_of_body_html` conditionné au droit `output.page_doc_link`

il faudrait revoir le code de ce footer !

un patch temporaire a été appliqué localement

**Comment by ghost** [comment]
Le thème a été modifié afin de corriger ce bug
